name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy HTML and Static Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 2213 -H mensa.pe >> ~/.ssh/known_hosts

      - name: Deploy using rsync over SSH
        run: |
          rsync -avz --delete --ignore-errors \
            -e "ssh -i ~/.ssh/id_ed25519 -p 2213" \
            *.html static ubuntu@mensa.pe:/var/www/html

      - name: Reload Nginx on server
        run: |
          ssh -i ~/.ssh/id_ed25519 -p 2213 ubuntu@mensa.pe \
            'sudo systemctl reload nginx'
